name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push the Docker images
      run: |
        docker build . --file Dockerfile.centos6 --tag ghcr.io/dah4k/soshell-centos6:latest
        docker build . --file Dockerfile.photon5 --tag ghcr.io/dah4k/soshell-photon5:latest
        docker push ghcr.io/dah4k/soshell-centos6:latest
        docker push ghcr.io/dah4k/soshell-photon5:latest
