name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push the Docker images
      run: |
        docker build . --file Dockerfile.centos6 --tag ghcr.io/dah4k/soshell-centos6:latest
        docker build . --file Dockerfile.photon5 --tag ghcr.io/dah4k/soshell-photon5:latest
        docker push ghcr.io/dah4k/soshell-centos6:latest
        docker push ghcr.io/dah4k/soshell-photon5:latest
